name: chart_app
description: Chart App
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.3.3 <4.0.0'
    flutter: '3.24.1'

dependencies:
    flutter:
        sdk: flutter
    deriv_chart:
        git:
            url: https://github.com/deriv-com/flutter-chart.git
            ref: master
    js: ^0.6.7

dev_dependencies:
    deriv_lint:
        git:
            url: https://github.com/deriv-com/flutter-deriv-packages.git
            path: packages/deriv_lint
            ref: dev
    flutter_test:
        sdk: flutter

flutter:
    fonts:
        - family: IBMPlexSans
          fonts:
              - asset: fonts/IBMPlexSans-Regular.woff2
              - asset: fonts/IBMPlexSans-Bold.woff2
                weight: 700
    uses-material-design: true
